name: Run Node Server

on:
  push:
    branches: [ main ]

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start server (testing only)
        run: |
          node server.js &
          sleep 5
          curl http://localhost:3000 || echo "Server not responding"
