name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Jalankan saat push ke branch main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Folder public HTML kamu

      - name: Deploy ke GitHub Pages
        uses: actions/deploy-pages@v4
